---
- name: Restart elasticsearch
  service: name=elasticsearch state=restarted
  notify: Wait for elasticsearch to be listening for connections

- name: Wait for elasticsearch to be listening for connections
  wait_for: port={{ es_etc_http_port | default(9200) }}
  when: es_wait_for_listen
